### ISSUE TITLE
[BUG] wrong calculation of position in EEPROM

### ISSUE THREAD

**Issue by TheMaskedDeveloper** [luc-github/ESP8266#445]
The position of EP_IS_DIRECT_SD  and following is one byte of respectively EP_TIME_SERVER3 is one byte shorter as described:

#define EP_TIME_SERVER3  722 //129 bytes 128+1 = string  ; warning does not support multibyte char like chinese
#define EP_IS_DIRECT_SD   850//1  bytes = flag
(EP_IS_DIRECT_SD  should be 851 i think)

**Comment by luc-github** [comment]
indeed - I do not know what I was thinking when I did that 😓   
 I have moved the max limit to 127 instead of 128 so no more overlap - this has low risk to happen but better prevent the problem 
https://github.com/luc-github/ESP3D/pull/447/commits/af0d8a0a9deba6d59db07e3ad73d7335eecb4e97
Thanks you for pointing this out

in 3.0 I will fix it differently
