### ISSUE TITLE
[BUG][ESP290] not working inside a macro

### ISSUE THREAD

**Issue by tmartin007** [luc-github/ESP8266#681]
**Describe the bug**

[ESP290] has no effect inside a macro

**To Reproduce**
1. Create a simple macro, e.g.:  
```
   G28XYZ
   M400
   G0X100Y100
   M400
   [ESP290] 1000 ; wait for 1 second
   G0Z50
```
2. Upload the macro to the ESP3D Filesystem
3. Use the Macro Editor to assign a button to the macro and save
4. execute the new macro by clicking on it's button
5. observe the macro executing
6. Notice, the command "[ESP290] 1000" is not causing the desired delay

**Expected behavior**
Line 5 of the same macro (above) "[ESP290] 1000" is expected to cause a 1 sec delay, before G0Z50 is executed.

**ESP3D Firmware:**
FW version:  2.1.1.b8 ESP8266/8586
WebUI version:  2.1b57
- Wifi mode: 11g 
- Flash method: [Arduino Ide]
- No change done in FW

**Target Firmware:**
 - Name: [Marlin]
 - Version [2.0.9.2]
 
**Board used (please complete the following information):**
Chip ID:  16455774
CPU Frequency:  160Mhz
Free memory:  35.53 KB
SDK:  2.2.2-dev(38a443e)
Flash Size:  1.00 MB

**Comment by luc-github** [comment]
[ESP290] is for ESP commands, it was made for pin states control, 
The Macro is not a real streamer but just simple sender, it send all commands one by one without waiting, so it send
```
   G28XYZ
   M400
   G0X100Y100
   M400
``` 
then wait 1 sec, but in same time your printer is processing the GCODE
then send
```
G0Z50
```
So you feel there is no pause but actually GCODE and pause are done in parallele because done on different board

I suggest you to use GCODE as it is in GCODE sequence to be controled
`G4 P1000`

**Comment by tmartin007** [comment]
Thanks for the thorough explanation!

G4 works beautifully. - Thanks again!

**Comment by luc-github** [comment]
Great  - you are welcome, I close issue then
