### ISSUE TITLE
[FEATURE REQUEST] Add VPN access via MqttVPN/Wireguard

### ISSUE THREAD

**Issue by rjjrbatarao** [luc-github/ESP8266#721]
**Is your feature request related to a problem? Please describe.**
Adding vpn directly to the esp8266/esp32 would make possibility or remote access from the cloud through proxy servers. It will be a cool feature as you can remotely access your esp32 dashboard anywhere without investing on raspberry pi and other openwrt linux.

**Describe the solution you'd like**
ESP8266/ESP32 -> wireguard/mqttvpn -> digital ocean /aws (as http proxy server) -> generated remote url ds8dfgf76.esp3s.com
As you can see its more line ngrok where it can generate remote url for global remote access.
I ve already done this setup but for my other projects non 3d printing related.

**Describe alternatives you've considered**
https://github.com/martin-ger/MQTT_VPN - works on esp8266/32                      /tcp   / slow
https://github.com/ciniml/WireGuard-ESP32-Arduino - esp32 only arduino ide     /udp  / fast
https://github.com/trombik/esp_wireguard - esp8266/esp32 esp idf                      /udp  /fast
Im trying to port wireguard to esp8266 arduino ide but i hit a wall when i couldn't find the solution on the lwip error code 8.

**Comment by luc-github** [comment]
but you already can access your esp3d webUI from internet if you setup properly NAT rules on your home server by forwarding the used ports.

I guess VPN is more secure but currently MQTT is not yet in plan : https://github.com/luc-github/ESP3D/issues/403#issuecomment-570889320
  
Above solutions could be considered in future - but due to my current workload on ESP3D / ESP3DLib / WebUi I do not have any bandwidth for such big feature in short/ middle term - unless you can handle it

**Comment by rjjrbatarao** [comment]
Thank you for your insight, in regards to nat port forwarding using dydns or duckns must be the cheapest way to do this without changes on the orginal code. I guess I have try to do a fork for my own development & research on this if it can handle vpn.
