### ISSUE TITLE
[FEATURE REQUEST] security by default

### ISSUE THREAD

**Issue by atsju** [luc-github/ESP8266#753]
**Is your feature request related to a problem? Please describe.**

All user are not security aware. A user not using passwords or using default passwords might experience security vulnerabilities if port is open on his box.
IMO `#define AUTHENTICATION_FEATURE` should be set by default.
Also, there is a password box not using ***** characters in the initial AP connection when configuring to host.

**Describe the solution you'd like**

- [ ] set `#define AUTHENTICATION_FEATURE` by default and user can deactivate it
- [ ] Use password box instead text box for host connection password during first connection
- [ ] make it mandatory to update default passwords at first connection
- [ ] Is it possible to have an explicit message when trying to access interface as `user` during first connection but failing because we need `admin` ? i.e. uploading idex.html.gz as user is not OK

Not security related (I might need to migrate this to webUI issues when I have time)
- [ ] it's anoying to need clicking on "set" for each box during initial setup. It should just be selected automatically when dropBox menu is selected.
- [ ] signaling when a restart is needed for parameters to be taken into account (for example when changing port parameters)

**Describe alternatives you've considered**

I understand this can be inconvenient for users that are only on local network. Maybe this could be configured at first connection (again, proposing WITH security as default choice)

**Additional context**

At this point I'm only planning on opening a port on my internet box and reviewing security level of connected device. Maybe I don't have all information at this point. 
Tests done on UI 2.1b57 and FW 2.1.1b10

**Comment by luc-github** [comment]
Authentication is not an 'option' to avoid to be disabled, so it is a define, because all function are hard coded and not optional.

Password is never sent to webui it actually send *********, so been in clear is not a problem, that said using password box it is already implemented in 3.x, same for multiple setting and one save button, same for restart message if setting need restart.

I am not in favor of setting authentication enable by default,  because it is not a setting to disable it but need reflash, also it will bring me too much sustaining work, people which open their network to outside should be aware of what they are doing and so check security feature.

**Comment by luc-github** [comment]
be noted there is no https support yet

**Comment by atsju** [comment]
Thanks for feedback. Great to see many of the little usage problems in 2.x have already been fixed in 3.x.

I fully understand autentication will bring more work. I still maintain my position but this may be done (much) later if real issues are discovered about it.

Feel free to close this issue if you think everything is addressed. I might open new issue in webUI usage when I try 3.x and all latest features.

**Comment by luc-github** [comment]
I close issue then
