### ISSUE TITLE
[FEATURE REQUEST] Use GPIO pin

### ISSUE THREAD

**Issue by svcru** [luc-github/ESP8266#762]
Hi, friend!
Could you bind the hardware pins of the esp to some events?
For example GPIO set to 1 when table/nozzle temperature is lower/higher than specified.
And vice versa, if you hang a button on the GPIO pin, then when you click on the button, some kind of script, for example, a gcode macro, will work.
Ideally, I would like to see a constructor in the web gui so that you can dynamically configure.
Thank you

**Comment by luc-github** [comment]
The lua interpretor has such purpose because not every user case can be hard coded - so the lua language should give the flexibility while keeping FW footprint small for everyone (https://github.com/luc-github/ESP3D/issues/378)
But even it is planned I did not have time to do real user case and see what functions / features need to be implemented in lua interpreter - right now only minimal functions are present: 
the webUI need to be as small as possible also so I doubt a contrstructor for script will be implemented - TBD

In all cases, this is edge case need, and so not in current priority list - but PR are welcome  as always
