### ISSUE TITLE
ESP3D upload file is unable to work with BTT TFTxx

### ISSUE THREAD

**Issue by alexgleb** [luc-github/ESP8266#783]
This is the main requirements of BTT TFT: 

General options which MUST be activated:

EEPROM_SETTINGS (in Configuration.h)
BABYSTEPPING (in Configuration_adv.h)
AUTO_REPORT_TEMPERATURES (in Configuration_adv.h)
AUTO_REPORT_POSITION (in Configuration_adv.h)
M115_GEOMETRY_REPORT (in Configuration_adv.h)
M114_DETAIL (in Configuration_adv.h)
REPORT_FAN_CHANGE (in Configuration_adv.h)

Options to support printing from onboard media:

SDSUPPORT (in Configuration.h)
LONG_FILENAME_HOST_SUPPORT (in Configuration_adv.h)
AUTO_REPORT_SD_STATUS (in Configuration_adv.h)
SDCARD_CONNECTION ONBOARD (in Configuration_adv.h)

**Comment by luc-github** [comment]
what is the error ?
Does your tft Fw has the bugfix https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/2431 ?

**Comment by alexgleb** [comment]
this is a scope
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware
esp3d is mounted in the TFT board

**Comment by luc-github** [comment]
it does not answer any of my questions

**Comment by alexgleb** [comment]
it does, I got the same problems of upload file, they met, though M20 and
M21 works perfectly, the main results: upload file does not work due BTT
TFT firmware communicates with Marlin.

**Comment by luc-github** [comment]
> the main results: upload file does not work due BTT
TFT firmware communicates with Marlin.

So issue is not ESP3D - why posting here ?

**Comment by alexgleb** [comment]
ESP3D is the main Issue :)

**Comment by alexgleb** [comment]
because it does not do the declared functionality

**Comment by alexgleb** [comment]
and an explanation looks like - others did it impossible  :)

**Comment by luc-github** [comment]
No, as you mentionned BTT communicate with Marlin this is Marlin/BTT issue, the protocol M28/M29 does not handle extra communication in same time -  when doing M28/M29 Marlin/TFT FW should not do anything else that why the fix I mentioned should be present, but you did not answered if it was present on your FW,

You did not answered what error is raised during upload neither - so I have no idea what error you have neither what is the possible root cause

Unlike ESP3D most of  softwares do not care if  the upload is correct or not,  they just stream the  data and the result can be hazardous because no check is done.

So I am not sure what do you expect from ESP3D to do with Marlin / TFT behavior

Anyway the M28/M29 protocol is dropped in new version of ESP3D because of such behavior not well handled by Marlin/Repetier/etc and  TFT FW  - so  there will have not fix ( is there any possible ?) unless you submit one

**Comment by alexgleb** [comment]
As a whole, it looks nice but 1 function of upload file does not work due
to the wrong implementation, I saw the 3.0 and installed. It looks like
much better
but to implement it in the whole scope it needs a lot of time. a year or
two . To fix such behavior it needs much less time.
I got a scope of errors with the upload file, mainly the cause is some
transfer data error due to the hardware functionality, for all cases, SD
works perfectly
but ESP3D does not do it. and I saw your explanations, I'm not happy with
this way of fan work. I'll fix it for myself when I find the solution.
because the upload file function needs to be reworked. it's not a big work.
but others should know about your unfinished work to do not waste time.

**Comment by luc-github** [comment]
what unfinished work? Sorry I do not understand

**Comment by Digifan** [comment]
Hi! All are finished. Thanks!

**Comment by alexgleb** [comment]
you have at least 2 defects, one at start when uploading it changes the
state of the board where ESP is mounted and another you use the same
websocket for all purposes uploading communications and so on and you
explain it as the defects on other sides :) Marlin,  BTT, others did your
defects :)

**Comment by alexgleb** [comment]
I believe when a work is not finished at some side and another work will
never finished on other side, people never get working version 3.0

**Comment by luc-github** [comment]
I still do not understand your explainations
1 -  ESP3D does not change state of board  
2 - websocket is not used for file upload
3 - I did not says other are defect - I said M28/M29 protocol do not allows others commands when working and so if others FW still send commands during upload there is no solution for ESP3D to fix it 

That said I really do not understand what you are doing 
1 - you report an issue but you ignore the issue template
2 - you also ignored the bot message telling you to use the template
3 - you ignored my questions to understand the error
4 - when I answered that you can contribute to fix the issue you saw -you talked about V3 and will need 1 or 2 years 
5 - you wrote ESP3D  has defects (I am sure it has several, it is definitly not bug free) but you describe issues not related to the title : you a not happy the way fan work, websocket, ESP3D 3.0 which does not support the M28/M29 feature because of M28/M29 reliability issue, and of course slow like hell speed

This is an open source project, I do on my free time, which means 
1 - anyone can use it
2 - anyone can contribute to it or do it's own version
3 - no one have to pay for it 

I really do not understand why you are so unhappy about this, you are not obliged to use it, you did not pay for it, but you are welcome to contribute  

So I think you are not looking for help but just trolling

I close issue as it goes nowhere

**Comment by alexgleb** [comment]
I'm not trolling, I'm not looking for help due to the project being created
long enough ago, a lot of work is done,and I can find some answers in the
history though I'm unhappy with these answers :)
Okay, NP, disable websocket and you will see the picture when communication
between ESP3D and MARLIN is stopped on the web console, for other boards ,
you can simulate such
communication for example M154 S10
after it, upload a file and ESP3D changes the STATE of BOARD where it is
mounted. perhaps, this issue is not ESP3D code but containing inside libs
websocket lib creates only 1 connection, you used it for all purposes
communication and uploading, though it should be separately
