### ISSUE TITLE
[Question] Switching between SPI and SDIO

### ISSUE THREAD

**Issue by pagabee** [luc-github/ESP8266#823]
Hello

I read in a [comment](https://github.com/luc-github/ESP3D/issues/794#issuecomment-1196329693), it is recommended to use a switch to share the SD card.
It is possible to switch between the SPI and the 4 bits SDIO protocol?
I mean the 3D printer board would communicate with the SD card via SPI and the ESP3D (ESP32) via SDIO.
The upload speed would be higher with SDIO but I don’t know if this kind of sharing would work or not.

**Comment by luc-github** [comment]
what is your SD sharing solution ? does your printer sd reader is supporting SDIO communications ?

**Comment by pagabee** [comment]
I have an MKS Robin nano V3 board with MKS wifi, but I’m not very satisfied with the MKS Marlin firmware, because it has a lot of small bugs.
The upload speed via MKS wifi is not so bad ~77kBs-100kBs, but it takes a many time to send a larger (~25MB) gcode file.
Therefore I want to find a solution for faster file upload.

The board does not support the SDIO.
My idea is shared SD with an additional board. SDIO communication with ESP32, SPI communication with the printer board.
As switching component I would use FST3257, FST3245 or similar IC.

**Comment by luc-github** [comment]
We are talking about an esp8266 chip do not expect miracle, you may increase a little bit the upload but I do not think so much - did you tried what the upload speed would be sdcard  card on esp8266 using arduino sample code https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266WebServer/examples/FSBrowser ?

From esp3d point of view it should be transparent because ESP3D will only use SDCard in sdio   when it control sdcard reader, so all should depend about your hardware switch, your SDCard reader, your sd card quality and your wiring.   
But currently there is not SDIO support for esp8266...

**Comment by pagabee** [comment]
I checked the upload speed on a ESP8266 board, it is ~155kBs.
