### ISSUE TITLE
[Question]<Can I embed index.html.gz into .bin file？>

### ISSUE THREAD

**Issue by liu2-3zhi** [luc-github/ESP8266#936]
Can I embed index.html.gz into .bin file?
index.html.gz needs to connect to wifi to upload manually every time, which is very troublesome.

**Comment by luc-github** [comment]
you should not have to upload index.html.gz each time you upload the FW only the first time
there are pluggins for arduino according the targeted filesystem: spiffs, littlefs, fat to upload the content of data directory from ide

Same.feature exists in platformio but it need an extra line that is not present in platformio.ini to define the filesystem and I never tested this process. so I cannot say more

Finally if your issue is to do several upload the best factory process is to build a complete image on targeted board then use esptool to dump it as full image and reuse it to flash fw+fs at once as many times as you need

**Comment by luc-github** [comment]
you are welcome
